// <auto-generated />
using System;
using CatchMore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatchMore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240201143741_TestDev-SQL_Reset")]
    partial class TestDevSQL_Reset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CatchMore.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 2, 1, 15, 37, 41, 149, DateTimeKind.Local).AddTicks(8772),
                            Latitude = 51.98807,
                            Longitude = 6.0045200000000003
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 2, 1, 15, 37, 41, 149, DateTimeKind.Local).AddTicks(8803),
                            Latitude = 52.98807,
                            Longitude = 6.2045199999999996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
